# Generated by Django 4.2.11 on 2026-04-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
