# Generated by Django 4.2.11 on 2026-05-18 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos_nuevos', models.BooleanField(default=True)),
                ('calificaciones_cambios', models.BooleanField(default=True)),
                ('tareas_recordatorios', models.BooleanField(default=True)),
                ('cuestionarios_eventos', models.BooleanField(default=True)),
                ('clases_programadas', models.BooleanField(default=True)),
                ('mensajes_recibidos', models.BooleanField(default=True)),
                ('email_habilitado', models.BooleanField(default=True)),
                ('whatsapp_habilitado', models.BooleanField(default=False)),
                ('sms_habilitado', models.BooleanField(default=False)),
                ('resumen_diario', models.BooleanField(default=False, help_text='Recibir resumen diario en lugar de notificaciones individuales')),
                ('hora_resumen', models.TimeField(default='09:00', help_text='Hora para recibir el resumen diario')),
                ('numero_whatsapp', models.CharField(blank=True, help_text='+506 XXXX XXXX', max_length=20)),
                ('numero_sms', models.CharField(blank=True, help_text='+506 XXXX XXXX', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Preferencias de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificacionMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('curso_creado', 'Nuevo curso creado'), ('calificacion_cambio', 'Cambio en calificación/aprobación'), ('tarea_recordatorio', 'Recordatorio de tarea sin entregar'), ('cuestionario_disponible', 'Cuestionario disponible'), ('cuestionario_cerrado', 'Cuestionario cerrado'), ('clase_programada', 'Clase programada'), ('mensaje_recibido', 'Nuevo mensaje')], max_length=30)),
                ('canales', models.CharField(max_length=100)),
                ('destinatarios_tipo', models.CharField(choices=[('admin', 'Administradores'), ('catequista', 'Catequistas'), ('participante', 'Participantes'), ('todos', 'Todos'), ('custom', 'Personalizado')], default='todos', max_length=50)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviando', 'Enviando'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio_real', models.DateTimeField(blank=True, null=True)),
                ('enviadas', models.IntegerField(default=0)),
                ('fallidas', models.IntegerField(default=0)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='notificaciones_masivas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curso_creado', 'Nuevo curso creado'), ('calificacion_cambio', 'Cambio en calificación/aprobación'), ('tarea_recordatorio', 'Recordatorio de tarea sin entregar'), ('cuestionario_disponible', 'Cuestionario disponible'), ('cuestionario_cerrado', 'Cuestionario cerrado'), ('clase_programada', 'Clase programada'), ('mensaje_recibido', 'Nuevo mensaje')], default='curso_creado', max_length=30)),
                ('canal', models.CharField(choices=[('en_app', 'En la aplicación'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='en_app', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('contenido_type', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido_id', models.IntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('icono', models.CharField(default='bi-bell', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx'), models.Index(fields=['usuario', '-fecha_creacion'], name='notificacio_usuario_b76847_idx')],
            },
        ),
    ]
