# Generated by Django 4.2.11 on 2026-05-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_perfil_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSacramental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_sacramento', models.DateField()),
                ('lugar_sacramento', models.CharField(max_length=255)),
                ('parroco', models.CharField(max_length=255)),
                ('fecha_bautizo', models.DateField(blank=True, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=255, null=True)),
                ('padrino', models.CharField(blank=True, max_length=255, null=True)),
                ('madrina', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(blank=True, limit_choices_to={'rol': 'PARTICIPANTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil')),
                ('sacramento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sacramentos.sacramento')),
            ],
        ),
    ]
