# Generated by Django 4.2.11 on 2026-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregatarea',
            name='archivo',
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='archivo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
