# Generated by Django 4.2.11 on 2026-04-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_entregatarea_archivo_entregatarea_archivo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregatarea',
            name='archivo_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
