# Generated by Django 4.2.11 on 2026-04-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_entregatarea_archivo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite_tardia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='permitir_tardia',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaterialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.URLField()),
                ('nombre', models.CharField(max_length=255)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='tareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.URLField()),
                ('nombre', models.CharField(max_length=255)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tareas.entregatarea')),
            ],
        ),
    ]
