# Generated by Django 4.2.11 on 2026-02-07 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_genero_alter_catequista_id_and_more'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='catequista',
        ),
        migrations.AddField(
            model_name='curso',
            name='catequistas',
            field=models.ManyToManyField(limit_choices_to={'rol': 'CATEQUISTA'}, related_name='cursos', to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_limite_inscripcion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
    ]
