# Generated by Django 4.2.11 on 2026-02-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_genero_alter_catequista_id_and_more'),
        ('cursos', '0002_remove_curso_catequista_curso_catequistas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('CANCELADO', 'Cancelado')], default='INSCRITO', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('participante', models.ForeignKey(limit_choices_to={'rol': 'PARTICIPANTE'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'unique_together': {('participante', 'curso')},
            },
        ),
    ]
