# Generated by Django 4.2.11 on 2026-03-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_genero_alter_catequista_id_and_more'),
        ('cursos', '0004_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('PERMISO', 'Permiso')], max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.clase')),
                ('participante', models.ForeignKey(limit_choices_to={'rol': 'PARTICIPANTE'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'unique_together': {('clase', 'participante')},
            },
        ),
    ]
