# Generated by Django 4.2.11 on 2026-05-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_envio_lista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='lista_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_sacramento',
            field=models.CharField(default='confirmacion', max_length=100),
            preserve_default=False,
        ),
    ]
