# Generated by Django 4.2.11 on 2026-05-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_fecha_envio_lista_curso_lista_enviada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_sacramento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
