# Generated by Django 4.2.11 on 2026-05-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_curso_tipo_sacramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='titulo',
            field=models.CharField(default='Clase', max_length=200),
        ),
    ]
