# Generated by Django 4.2.11 on 2026-05-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_clase_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tipo_sacramento',
        ),
    ]
