# Generated by Django 4.2.11 on 2026-05-17 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0001_initial'),
        ('cursos', '0009_remove_curso_tipo_sacramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='sacramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sacramentos.sacramento'),
        ),
    ]
