# Generated by Django 4.2.11 on 2026-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_genero_alter_catequista_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
