# Generated by Django 4.2.11 on 2026-05-07 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0006_curso_fecha_envio_lista_curso_lista_enviada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('sacramento', models.CharField(max_length=100)),
                ('promedio_tareas', models.FloatField()),
                ('promedio_cuestionarios', models.FloatField()),
                ('faltas', models.IntegerField()),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True)),
                ('certificado_enviado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
