# Generated by Django 4.2.11 on 2026-05-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_qr'),
        ('aprobaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprobado',
            name='certificado_enviado',
        ),
        migrations.AlterField(
            model_name='aprobado',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.participante'),
        ),
    ]
