# Generated by Django 4.2.11 on 2026-05-08 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_qr'),
        ('cursos', '0007_alter_curso_tipo_sacramento'),
        ('aprobaciones', '0002_remove_aprobado_certificado_enviado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprobado',
            options={'ordering': ['-fecha_aprobacion']},
        ),
        migrations.AddField(
            model_name='aprobado',
            name='enviado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aprobado',
            name='estado_final',
            field=models.CharField(default='APROBADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='aprobado',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aprobado',
            name='participante',
            field=models.ForeignKey(limit_choices_to={'rol': 'PARTICIPANTE'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='aprobado',
            name='promedio_cuestionarios',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='aprobado',
            name='promedio_tareas',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='aprobado',
            unique_together={('participante', 'curso')},
        ),
    ]
