# Generated by Django 4.2.11 on 2026-05-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_qr'),
        ('aprobaciones', '0003_alter_aprobado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprobado',
            name='apellido_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aprobado',
            name='nombre_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprobado',
            name='participante',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'PARTICIPANTE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
