# Generated by Django 4.2.11 on 2026-05-10 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_clase_titulo'),
        ('aprobaciones', '0004_aprobado_apellido_manual_aprobado_nombre_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobado',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso'),
        ),
    ]
