# Generated by Django 4.2.11 on 2026-05-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacramentos', '0001_initial'),
        ('usuarios', '0005_perfil_qr'),
        ('cursos', '0010_curso_sacramento'),
        ('aprobaciones', '0005_alter_aprobado_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('promedio_tareas', models.FloatField(default=0)),
                ('promedio_cuestionarios', models.FloatField(default=0)),
                ('faltas', models.IntegerField(default=0)),
                ('estado_final', models.CharField(choices=[('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], max_length=20)),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
                ('enviado_automaticamente', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('participante', models.ForeignKey(limit_choices_to={'rol': 'PARTICIPANTE'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('sacramento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sacramentos.sacramento')),
            ],
            options={
                'ordering': ['-fecha_resultado'],
                'unique_together': {('participante', 'curso')},
            },
        ),
        migrations.DeleteModel(
            name='Aprobado',
        ),
    ]
